
<h3>Adicionar Funcionário</h3>


    <form role="form" method="post" class="form-horizontal">


            <div class="form-group">
                <label for="nome" class="control-label">Nome</label>
                <div class="col-sm-13">
                    <input type="text" name="nome" placeholder="Nome" required>
                </div>
            </div>

            <div class="form-group">
                <label for="cpf" class="control-label" >CPF</label>
                <div class="col-sm-13">
                    <input type="text" name="cpf" placeholder="CPF" required>
                </div>
            </div>

            <div class="form-group">
                <label for="salario" class="control-label">Salário</label>
                <div class="controls">
                    <input type="text" name="salario" placeholder="Salário" required>
                </div>
            </div>

            <input type="submit" value="Adicionar" class="bnt btn-default">


    </form>

<?php echo $this->resp; ?>

<a href="<?php echo $this->url('application/default', array('controller' => 'index', 'action' => 'lista')); ?>">Listar Funcionario</a>



